### PR TITLE
add multi-backend support to pure structure and recording

### PR DESCRIPTION
**Pull request by peuter**
also fix replaying xhr responses that are delayed

### CODE REVIEW

**Comment by ChristianMayer** [comment]
The demo config worked fine, but demo_flat creates lots of error messages when e.g. playing with the color chooser:
grafik

**Comment by peuter** [comment]
Should work now

**Comment by ChristianMayer** [comment]
Error messages have gone, but changing any actor in demo_flat doesn't show a reaction. Neither on the network pane (no "r" are sent) nor on any other actors that use the same address.

Also in the console I get this message that shouldn't be possible as no communication should go to `/cgi-bin/` directly:
grafik

**Comment by peuter** [comment]
The read request should work now, the GET-Request to cgi-bin/ is not reproducable for me.

**Comment by ChristianMayer** [comment]
This works, but the 403 and the direct call to `/cgi-bin/` is still here. 
Going into the debugger I see a strange mixup up knxd and openhab:
grafik

**Comment by peuter** [comment]
Do you have a openhab backend url configured somewhere? What are the cometvisu specific headers that are send with the config response?

**Comment by ChristianMayer** [comment]
Ok, that leads to the right direction:
grafik
But I haven't configured OpenHAB in the Docker container:
grafik

**Comment by ChristianMayer** [comment]
Looking at https://github.com/CometVisu/Docker/blob/master/CometVisuBase/cometvisu-entrypoint#L40-L64 I think this is (currently) an expected behavior

**Comment by peuter** [comment]
Yes I just checked that too, I think we should delete this line https://github.com/CometVisu/Docker/blob/master/CometVisuBase/cometvisu-entrypoint#L40

I will also change this pull request to handle the backend names as comma separated list correctly, I wasn't aware that this is allowed. Then I will only create clients for the backends that are in that list. That should fix your problem too.

**Comment by ChristianMayer** [comment]
Is is safe (backward compatible) to delete this line 40?

**Comment by peuter** [comment]
> Is is safe (backward compatible) to delete this line 40?

I don't remember if we ever had a release where you had to use the CGI-URL variable to configure the path to the openhab backend. But its clearly wrong if someone did that, so I would take the risk to find someone who has this kind of configuration and make him fix it by removing this behavior.

**Comment by peuter** [comment]
btw as CGI_URL_PATH is deprecated you should remove it from your configuration.

**Comment by ChristianMayer** [comment]
> btw as CGI_URL_PATH is deprecated you should remove it from your configuration.

I know, it's in there due to laziness and testing what's happening to a user who didn't remove it :)

**Review by ChristianMayer — APPROVED** [review]

**Pull request merged**
