### PR TITLE
Do not process influx data by backend processors, because it is alrea…

### LINKED ISSUE #1312: v0.12.x: Diagrams fail with "TypeError: t is undefined"
I'm running CometVisu 0.11.2 successfully under Apache/PHP 8.1 with openhab 3.x and influxdb.
I recently tried to upgrade CometVisu to 0.12.1 and all values are displayed correctly (so the connection to openhab/influxdb works) but none of the diagrams with data from InfluxDB are displayed but a TypeError appears. I also tried v0.12.0 with the same result.
I tried to debug this and found that influxfetch.php receives an answer of about 7kB of JSON data before the error message appears:

```
TypeError: t is undefined
 in file http://192.168.XXX.XXX/cv/index.js
 line 39
Normalized Stack:  
        http://192.168.XXX.XXX/cv/index.js:39:190704
        http://192.168.XXX.XXX/cv/package-3.js:1:5327
        http://192.168.XXX.XXX/cv/package-3.js:1:5006
        http://192.168.XXX.XXX/cv/index.js:14:523041
        http://192.168.XXX.XXX/cv/index.js:14:561674
        http://192.168.XXX.XXX/cv/index.js:14:523006
        http://192.168.XXX.XXX/cv/index.js:14:522912
        http://192.168.XXX.XXX/cv/index.js:14:484150
        http://192.168.XXX.XXX/cv/index.js:14:494623
        http://192.168.XXX.XXX/cv/index.js:14:561674
        http://192.168.XXX.XXX/cv/index.js:14:494582
        http://192.168.XXX.XXX/cv/index.js:14:496958
        http://192.168.XXX.XXX/cv/index.js:39:156714
        http://192.168.XXX.XXX/cv/index.js:39:156181
        http://192.168.XXX.XXX/cv/index.js:39:155759
        http://192.168.XXX.XXX/cv/index.js:14:491737
        http://192.168.XXX.XXX/cv/index.js:39:405488
        http://192.168.XXX.XXX/cv/index.js:39:409207
        http://192.168.XXX.XXX/cv/index.js:39:409003
        http://192.168.XXX.XXX/cv/index.js:14:394921
        http://192.168.XXX.XXX/cv/index.js:14:557028
```

### PR DESCRIPTION
**Pull request by peuter**
…dy in the right format. Fix openHAB backend client data processing.

closes #1312

### CODE REVIEW

**Review by peuter — COMMENTED** [review]
revert some changes, the openhab perstistance service data must contain a "data" property

**Comment by ChristianMayer** [comment]
This should be a pull request against `develop` and not `master`

**Comment by peuter** [comment]
> This should be a pull request against `develop` and not `master`

No this is a bugfix for the 0.12.x release, which is developed and released in the master branch. It also needs to be done for the develop branch, but that is not ready yet. I still have to check if a simple cherry-pick is possbile or if it needs more changes as the backend implementation is different in the develop branch (due to the multi-backend support).

**Comment by ChristianMayer** [comment]
But I thought we had the release-0.12 branch for that?

**Comment by peuter** [comment]
Please read my last comment in gitter where I explained that. The "latest" release needs to be build from the master-branch, otherwise things do not work right (e.g. docker tagging). The whole CI process is build for the following setup:

- master-branch: latest release
- develop-branch: testing releases (aka nighty builds)
- release-x.x branches: legacy releases

**Comment by ChristianMayer** [comment]
We should continue that discussion on Gitter. As it must end up in master anyway I'll pull it to save some time

**Review by ChristianMayer — APPROVED** [review]

**Pull request merged**
