### PR TITLE
Feature/unit tests

### PR DESCRIPTION
**Pull request by peuter**
introduces unit-testing (grunt karma:travis) and end-to-end tests (grunt e2e) to the CometVisu.

Some basic tests are implemented to show how its done as a basis for further tests. Tests can be found in the test subdirectory (*.spec.js files). They are split into karma (unit-tests) and protractor (end-to-end tests).

### CODE REVIEW

**Comment by peuter** [comment]
This is meant as a preparation for #252 . When we have reached a certain coverage of tests, refactoring should be easier as you will find regressions automatically.

**Comment by ChristianMayer** [comment]
I think there are a few wrong files in this pull request like src/designs/metal/basic.css

**Comment by peuter** [comment]
nope those are fixes for bugs found by the unit/e2e tests, removing them would lead the tests to fail.

**Comment by peuter** [comment]
I am closing this one because I solved the merge conflict in another branch, new PR is following right away.

**Pull request closed without merging**
