### PR TITLE
Gauge improvements

### PR DESCRIPTION
**Pull request by starwarsfan**
Changed the position of title and unit text on radial bargraphs. So now the unit text is located on the empty space on the bottom between the ends of the radial gauge and the title text is located right above the lcd where the unit text was located before. Additionally increased the font size a little bit for better readability. Compare screenshots:

Before:
image

After:
image

### CODE REVIEW

**Comment by joltcoke** [comment]
Could you please squash the commits? The result looks good, but out of 14 commits only 1 is relevant.

**Comment by starwarsfan** [comment]
[x] Squashing done :+1:

**Comment by ChristianMayer** [comment]
I see two points:
1) I like the new version better
2) I don't like to modify an external lib as this will create problems when it will be updated in the future. Nobody will remember these changes in the long run.

=> Probably it's best to get this change included upstream and then pull the new lib version here

**Comment by starwarsfan** [comment]
I see your point and aggree. But I don't know, that this is an external component!? So where does it came from? Where should I put in the pull request?

**Comment by ChristianMayer** [comment]
I don't really know - but I guess it's from https://github.com/HanSolo/SteelSeries-Canvas

**Comment by starwarsfan** [comment]
Opened https://github.com/HanSolo/SteelSeries-Canvas/pull/21 on upstream of used library.

**Pull request closed without merging**
