### PR TITLE
use indexedDB instead of localStorage

### PR DESCRIPTION
**Pull request by peuter**
because it has no such low limits for quota. This avoids broken cache due too quota exceeded exceptions.

### CODE REVIEW

**Comment by ChristianMayer** [comment]
Trying the code (Chrome, HTTPS connection) I can see that IndexDB has one object storage.

But looking at it it seems that nothing gets stored: "Total entries: 0"
grafik

**Comment by peuter** [comment]
Please keep in mind, that caching is disabled in source builds. You have to explicitly enable it with enableCache=true

**Comment by ChristianMayer** [comment]
Thanks for the hint, that was the reason.

But, different issue, with URL `.../?enableCache=true#id_`:
grafik

**Comment by peuter** [comment]
Ah right, I did not test with the default config (with no name). The name is used as key in the DB. That obviously does not work when there is no name. Will fix that soon. But it should work with configs with names.

**Comment by ChristianMayer** [comment]
Yes, config with not-default-name worked fine

**Comment by peuter** [comment]
default should work now too

**Review by ChristianMayer — APPROVED** [review]

**Pull request merged**
