### PR TITLE
added readonly mode for slider

### PR DESCRIPTION
**Pull request by tuxedo0801**
if readonly, just show the value/slider position, but disable user interaction.

### CODE REVIEW

**Comment by joltcoke** [comment]
The address item has a mode attribute. Would it be possible to set the slider to readonly if the address mode is "read"?

What happens if readonly is false and mode is read? You still can move the slider but nothing will happen (on the bus)?

**Comment by joltcoke** [comment]
Label: Enhancement
Milestone: 1.0.0

**Comment by tuxedo0801** [comment]
> Would it be possible to set the slider to readonly if the address mode is "read"?

Maybe. My JS skills are not sooo good.

> What happens if readonly is false and mode is read? You still can move the slider but nothing will happen (on the bus)?

with the current PR, if readonly="true", you cannot move the slider at all. It's just showing the value, independant from mode-attribute of address-item.

**Comment by joltcoke** [comment]
var disable = true;

for (var ga in data.address) {
  if(data.address[ga][1] & 2) {
    disable = false;
    break;
  }
}

Should do the trick. You can now use the disable variable to deactivate the widget. sliders without any address will also get disabled.

**Comment by tuxedo0801** [comment]
Could you pls. explain 

```javascript
if(data.address[ga][1] & 2)
```
?

Am I right that the attribute-order or address-item is relevant?

**Comment by joltcoke** [comment]
Sure!

data.address contains all GA's associated with the widget. Since it is an Javascript Object you can not access it with numeric indices. You either have to use a for ... in loop or know the index beforehand.

Index is the address name as supplied in the config XML. Each address will have three fields, indexed numerically:

0: transform
1: disable/read/write/readwrite mode (Bit 0: read, Bit 1: write)
2: variant

Attribute order in the config file is not relevant, it will always mapped according to the above rules. The code i've posted above will loop over all addresses configured for the widget. If there is at least one with write access, disabled will be false. If there is no address at all or all of them are configured read only, disable will be true.

**Comment by tuxedo0801** [comment]
Thanks for explanation. Tested, Works. Will update the PR.

**Comment by tuxedo0801** [comment]
implementation updated accordingly.

**Pull request merged**
