### PR TITLE
fix rsslog datetime value transformation + icon appearance in popup

### LINKED ISSUE #627: RSSLog plugin shows no date
(see: https://knx-user-forum.de/forum/supportforen/cometvisu/1133276-rückmeldung-zur-aktuellen-entwicklungsversion-nach-umstieg-auf-qooxdoo?p=1139906#post1139906)

`rsslog.php` seems only to be compatible with PHP < 5.4.0 which is rather outdated. So this should be fixed be someone using the wiregate, to be able to verify the error and test the fix.

And/Or make the PHP-part of the plugin compatible with PHP 7. Using PDO as abstraction layer might be an option here, but it needs to be verified that this is available on wiregate too

### PR DESCRIPTION
**Pull request by peuter**
closes #627

### CODE REVIEW

**Comment by peuter** [comment]
@ChristianMayer If this fix does not work, please record a log for me. I can see what going wrong then.

**Comment by ChristianMayer** [comment]
Log sent by mail

**Comment by ChristianMayer** [comment]
Icons are looking fine now.

But there's still an issue: when you click on an entry (first click opens a pop up, I'm talking about the click in the popup) you can "confirm" an item. This will change the icon and strike through the text.
The display of a confirmed item is fine - but the confirmation itself doesn't work: only the strike is shown but the icon isn't updated and the confirmation isn't stored.
Looking at the network is seems that there's a problem by sending a wrong "number" for `u`: `rsslog.php?u=undefined&state=1`
(Note that's the case most of the time, one of the entries did work...)

**Comment by peuter** [comment]
Ok, found and fixed.

**Pull request merged**
