### PR TITLE
allow editing of 'custom' childs (where no schema support is given, e…

### PR DESCRIPTION
**Pull request by peuter**
….g. used for user plugins that are not known to the schema) by just editing the outerHTML content in a TextArea and validate if its valid XML code.

Example config code:
```xml
	<page name="Start">
		<line>
			<layout colspan="12" />
		</line>
		<text align="center">
			<label>Welcome to the CometVisu!</label>
		</text>
		<line>
			<layout colspan="12" />
		</line>
		<custom><test attr1="val1" attr2="attr2">1</test></custom>
	</page>
```

### CODE REVIEW

**Comment by ChristianMayer** [comment]
Adding a `custom` element in a quite empty config doesn't work and displays on the console
```
Native.js:48 032382 cv.ui.manager.editor.Tree[2558-0]: TypeError: Cannot read property 'replaceChild' of null
https://timberwolf76.local/proxy/visugit/obiwan/transpiled/cv/ui/manager/model/XmlElement.js:1043:36,Array.forEach (<anonymous>),https://timberwolf76.local/proxy/visugit/obiwan/transpiled/cv/ui/manager/mo…local/proxy/visugit/obiwan/transpiled/cv/ui/manager/editor/Tree.js:1994:21
```

**Comment by peuter** [comment]
> Adding a custom element in a quite empty config doesn't work and displays on the console

Fixed

**Comment by ChristianMayer** [comment]
grafik
-> `die Attribute` => `den Inhalt` (we are editing much more than only the attributes)

grafik
-> `Element Attribute` => `Element Inhalt`

**Comment by peuter** [comment]
Edit dialog texts are updated

**Review by ChristianMayer — APPROVED** [review]

**Pull request merged**
