### PR TITLE
Switch icon to svg

### PR DESCRIPTION
**Pull request by ChristianMayer**
Make icons use a (very :() big SVG file instead of the many little PNG files.

### CODE REVIEW

**Comment by ChristianMayer** [comment]
This pull request solves https://github.com/CometVisu/CometVisu/issues/336.

But note: the currently(?) generated SVG file is very big - 6.5 MB. Zipping it makes it more acceptable, but even then it's 1 MB big.

I'm not sure whether we want to give every user such a big impact when they are most likely using only a small subset of the icons.

**Comment by peuter** [comment]
I would suggest to move this one to an extra branch in the main repo, as I did some tweaks when I tried to generate a webfont from the SVG Icons, which could be useful here too. Those tweaks fixed some problems and significantly decreased the size of each SVG (by 30-40% as far as I remember).

**Comment by ChristianMayer** [comment]
OK, it's now in https://github.com/CometVisu/CometVisu/tree/switch_icon_to_svg

**Comment by ChristianMayer** [comment]
Will be replaced by the PR on the CometVisu/CometVisu branch.

**Pull request closed without merging**
