### PR TITLE
Ignore Eclipse project files

### PR DESCRIPTION
**Pull request by SirTobiIV**
Ignore Eclipse project files in github project

### CODE REVIEW

**Comment by peuter** [comment]
This pull request is empty. Did you forget to commit or push the changes?

**Comment by SirTobiIV** [comment]
I ahve no idea what went wrong. I did add 4 files to the gitignore list.
I selected the changed file and clicked on commit in the github tool. See Screenshot. The problem is now even the commit button is gone.
github empty commit

**Comment by peuter** [comment]
Hard to tell what went wrong from here. If you already commited the changes it might explain, why the commit button isn't visible, because there are no changes to commit. But I'm just guessing cause I don't now the tool you are using. Did you push your changes?

**Comment by SirTobiIV** [comment]
What does "push " mean? There is no such Button or menu available. 
Can I somehow delete or cancel  the pull request to try again?

**Comment by peuter** [comment]
Usually you work with a local copy (called clone) of your github repository. A commit stores the changes in your local repository, a push sends your local changes to yout github repository and from there you create your pull requests.

**Comment by peuter** [comment]
This page may help you to understand the git basics needed here: http://test.cometvisu.org/CometVisu/de/manual/colab/index.html

**Pull request merged**
