### PR TITLE
Fix DPT6.010

### PR DESCRIPTION
**Pull request by ChristianMayer**
and also make DPT5.004 more robust by ensuring the data range

This will fix https://knx-user-forum.de/forum/supportforen/cometvisu/940121-dpt-6-010

### CODE REVIEW

**Comment by peuter** [comment]
Could you please also integrate the changes from commit 627015e746a08bccfa55c20622fbabdbeb9fc967 to fix the build either be also cherry-picking or as it is a tiny change by manually editing the package.json? Feels better to accept PR with working builds, altough in this version the build does not do that much :-)

**Comment by ChristianMayer** [comment]
Picked it. But it seems it didn't help :(

BTW: please also cherry pick your commit that should go into the 0.9.2

**Comment by peuter** [comment]
Ok seems as if this one is also needed 2b72ee375dada5c990a9dc2565a048dcc9843ab6

Will check which commit should be part of 0.9.2 tomorrow.

**Comment by ChristianMayer** [comment]
Better now :)

**Pull request merged**
