### PR TITLE
fix button animation

### PR DESCRIPTION
**Pull request by peuter**
this is a work-in-progress PR to solve the issues mentioned in #606. As currently #606 does not contain a complete description of the known errors/misbehaviours, this PR handles only the known problem.

Initially these are:
* fixes button animation for all widgets using the HasAnimatedButton mixin (see http://cometvisu.org/CometVisu/en/latest/api/#cv.ui.common.HasAnimatedButton for a complete list). To test the fix, follow these steps: mouse-down on e.g. a trigger, move outside the trigger (button state changes to unpressed), move inside the trigger (button state changes to pressed), mouse-up

refs #606

### CODE REVIEW

**Comment by peuter** [comment]
closes #606

**Comment by ChristianMayer** [comment]
Tests with Chrome on a desktop with a mouse (i.e. not a mobile device):
* GestureCore.js:210 is contaminating the console.log
* Pushbutton (at least on demo config) now looking always pressed
* Clicking on the slider (instead of dragging it) doesn't always update the value

**Comment by peuter** [comment]
* console.log removed
* Pushbutton: working fine for me. Only looking pressed when I change the switch abote to 'An' or use the pushbutton itself

**Comment by peuter** [comment]
I am also not able to reproduce the slider problem.

**Comment by peuter** [comment]
Ok, I added the listener to the sliders parent widget. Should be easier to use now, as you do not have to click exactly on the slider range. I assume thats was the problem with your missing slider updates.

**Comment by ChristianMayer** [comment]
confirming Console.log fix.
But the pushbutton and slider is still broken.
The idea to make the slider react to outside clicks can be a good choice when the design decides to make the sliding-bar very thin. But for "normal" designs it will cause more troubles as clicks (very) left or right of the slider will also move it.
The issue I was describing also aren't related to miss the active area as the handle is moving - but the new values aren't always sent to the bus.

=> I suggest that 4ccdf64 is reverted and the pushbutton is fixed before this PR is merged. The uncommunicative slider can then be researched and fixed somewhere else as it's not an animation issue

**Comment by ChristianMayer** [comment]
I guess the pushbutton is a type issue (number vs. string):
grafik

**Comment by peuter** [comment]
Ok, done.

**Pull request merged**
